spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/inventory?useSSL=false&serverTimezone=UTC
    username: root
    password: 'root'
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: mandukart770@gmail.com
    password: "oggw wpyz eboc uaki"
    properties:
      mail:
        SMTP:
          auth: true
          STARTTLS:
            enable: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

springdoc:
  swagger-ui:
    path: /docs

