spring:
  application:
    name: auth-service

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

#
#    spring.mail.host=smtp.gmail.com
#    spring.mail.port=587
#    spring.mail.username=mandukart770@gmail.com
#    spring.mail.password=oggw wpyz eboc uaki
#    spring.mail.properties.mail.smtp.auth=true
#    spring.mail.properties.mail.smtp.starttls.enable=true