plugins {
    id 'java-library'
    id 'io.spring.dependency-management' version '1.1.0'
}

group = 'com.skillswap.common'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:3.2.5"
    }
}

dependencies {

    /* Spring */
    api 'org.springframework:spring-web'
    api 'org.springframework:spring-context'
    api 'org.springframework.security:spring-security-core'

    /* Validation */
    api 'jakarta.validation:jakarta.validation-api'

    /* Jackson */
    api 'com.fasterxml.jackson.core:jackson-annotations'

    /* Lombok */
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
}
