plugins {
    id 'java-library'
}

group = 'com.skillswap.common'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    api 'org.springframework:spring-web'
    api 'org.springframework:spring-context'
    api 'org.springframework:spring-security-core'
    api 'jakarta.validation:jakarta.validation-api'

    compileOnly 'org.projectlombok:lombok:1.18.32'
    annotationProcessor 'org.projectlombok:lombok:1.18.32'
}